// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StatsSvrClient is the client API for StatsSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatsSvrClient interface {
	GetRankList(ctx context.Context, in *RankListReq, opts ...grpc.CallOption) (*RankListRsp, error)
}

type statsSvrClient struct {
	cc grpc.ClientConnInterface
}

func NewStatsSvrClient(cc grpc.ClientConnInterface) StatsSvrClient {
	return &statsSvrClient{cc}
}

var statsSvrGetRankListStreamDesc = &grpc.StreamDesc{
	StreamName: "GetRankList",
}

func (c *statsSvrClient) GetRankList(ctx context.Context, in *RankListReq, opts ...grpc.CallOption) (*RankListRsp, error) {
	out := new(RankListRsp)
	err := c.cc.Invoke(ctx, "/StatsSvr/GetRankList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatsSvrService is the service API for StatsSvr service.
// Fields should be assigned to their respective handler implementations only before
// RegisterStatsSvrService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type StatsSvrService struct {
	GetRankList func(context.Context, *RankListReq) (*RankListRsp, error)
}

func (s *StatsSvrService) getRankList(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.GetRankList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/StatsSvr/GetRankList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.GetRankList(ctx, req.(*RankListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterStatsSvrService registers a service implementation with a gRPC server.
func RegisterStatsSvrService(s grpc.ServiceRegistrar, srv *StatsSvrService) {
	srvCopy := *srv
	if srvCopy.GetRankList == nil {
		srvCopy.GetRankList = func(context.Context, *RankListReq) (*RankListRsp, error) {
			return nil, status.Errorf(codes.Unimplemented, "method GetRankList not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "StatsSvr",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "GetRankList",
				Handler:    srvCopy.getRankList,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "stats.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewStatsSvrService creates a new StatsSvrService containing the
// implemented methods of the StatsSvr service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewStatsSvrService(s interface{}) *StatsSvrService {
	ns := &StatsSvrService{}
	if h, ok := s.(interface {
		GetRankList(context.Context, *RankListReq) (*RankListRsp, error)
	}); ok {
		ns.GetRankList = h.GetRankList
	}
	return ns
}

// UnstableStatsSvrService is the service API for StatsSvr service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableStatsSvrService interface {
	GetRankList(context.Context, *RankListReq) (*RankListRsp, error)
}
